### ISSUE TITLE
Use Manifest Attribute Bundle-Version if Hook-Version is not defined

### ISSUE THREAD

**Issue by kschmiechen** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.interceptor-manager#87]
### Description

The HookManifestUtils currently try to extract the hook version from the manifest attribute `Hook-Version`.  
https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.extension.interceptor-manager/blob/e931e587aa08782228c9619508496ef54dd72431/src/main/java/ch/sbb/polarion/extension/interceptor_manager/util/HookManifestUtils.java#L30

### Motivation

When developing in Eclipse, the manifest attribute `Bundle-Version` anyway needs to be defined (afaik).

### Proposed Solution (optional)

I suggest to update the above line to one of the following two:

- `return attributes.getValue("Hook-Version") != null ? attributes.getValue("Hook-Version") : attributes.getValue("Bundle-Version");`
- `return attributes.getValue("Bundle-Version");`

**Comment by grigoriev** [comment]
@kschmiechen, 

as far as I know, `Bundle-Version` is not a mandatory attribute for the manifest. According to the information I found [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=535115), this is a bug in Eclipse.

Moreover, the hooks for interceptor-manager are not OSGi bundles, so in this case we wanted to explicitly separate `Bundle-Version` and `Hook-Version`.
